trainer: energy

dataset:
  # - src: data/is2re/100k/train/binaryCu-relax.lmdb
  #   normalize_labels: True
  #   target_mean: -1.1586277916941128
  #   target_std: 2.2921039048525236
  # - src: data/is2re/all/val_id/binaryCu-relax.lmdb
  #   normalize_labels: True
  #   target_mean: -1.1586277916941128
  #   target_std: 2.2921039048525236

  - src: data/is2re/all/train/binaryCu-relax-split.lmdb
    normalize_labels: True
    target_mean: -1.1955971954016584
    target_std: 2.279836063743405
  - src: data/is2re/all/val_id/binaryCu-relax.lmdb
    normalize_labels: True
    target_mean: -1.1955971954016584
    target_std: 2.279836063743405
  # - src: data/is2re/all/test_id/binaryCu-relax-split.lmdb
  #   normalize_labels: True
  #   target_mean: -1.1955971954016584
  #   target_std: 2.279836063743405

# logger: tensorboard
logger: None
is_hpo: True

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
