trainer: multitask_thresh

dataset:
  - src: /home/chrispr/mem/chrispr/catalysis/ocp/data/aug_thresh_strained_full_structures/binaryCu-relax-moleculesubset_train.lmdb
    normalize_labels: False
    target_mean: -0.08756357
    target_std: 1.97406909
  
  - src: /home/chrispr/mem/chrispr/catalysis/ocp/data/aug_thresh_strained_full_structures/binaryCu-relax-moleculesubset_valid.lmdb
  
  - src: /home/chrispr/mem/chrispr/catalysis/ocp/data/aug_thresh_strained_full_structures/binaryCu-relax-moleculesubset_test.lmdb
   
# inference
  # - src: /home/chrispr/mem/chrispr/catalysis/ocp/data/inference_aug_strained_full_structures/traindomain_inference.lmdb
   
logger: tensorboard

task:
  dataset: single_point_lmdb
  num_targets: 6
  loss_balance: 0.1
  description: "Relaxed state energy prediction from initial structure."
  type: classification
  metric: mae
  labels:
    - relaxed energy

model:
  name: dimenetplusplus_strain
  hidden_channels: 17
  out_emb_channels: 23
  num_blocks: 2
  cutoff: 7. # should this match the a2g radius in the dataset? probably. or is this for regenerating graph on the fly..
  num_radial: 4 # size of the basis set
  num_spherical: 4 # size of the basis set
  num_before_skip: 1
  num_after_skip: 1
  num_output_layers: 3
  regress_forces: False
  use_pbc: True
  num_graph_targets: 3
  strain_projection_channels: 14
  num_strain_layers: 4
  strain_final_dim: 4

optim:
  batch_size: 8
  # eval_batch_size: 16
  num_workers: 4
  lr_initial: 0.001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 60000
    - 120000
  warmup_steps: 1000
  warmup_factor: 0.2
  max_epochs: 140
  
#checkpoint: ../checkpoints/train/2021-11-22-21-08-00/best_checkpoint.pt
#strict_load: False