includes:
#   - configs/is2re/10k/base.yml
   - /mnt/io2/scratch_vshenoy1/chrispr/catalysis/ocp/configs/baseline_train/binaryCu-hpo.yml

model:
  name: schnet
  hidden_channels: 256
  num_filters: 128
  num_interactions: 3
  num_gaussians: 100
  cutoff: 7.0
  use_pbc: True
  regress_forces: False

# *** Important note ***
#   The total number of gpus used for this run was 1.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 64
  # eval_batch_size: 64
  num_workers: 4
  lr_initial: 0.005
  lr_gamma: 0.1
  lr_milestones: # epochs at which lr_initial <- lr_initial * lr_gamma
    - 2500
    - 5000
    - 7500
  warmup_steps: 350
  warmup_factor: 0.2
  max_epochs: 250
