includes:
# - configs/is2re/100k/binaryCu.yml
#  - ../ocp/configs/is2re/10k/base_multitarget.yml
#  - ../ocp/configs/baseline_train/base_multitarget.yml
  - /mnt/io2/scratch_vshenoy1/chrispr/catalysis/ocp/configs/baseline_train/base_multitarget_strain.yml

model:
  name: dimenetplusplus_strain
  hidden_channels: 24
  out_emb_channels: 12
  num_blocks: 3
  cutoff: 7. # should this match the a2g radius in the dataset? probably. or is this for regenerating graph on the fly..
  num_radial: 5 # size of the basis set
  num_spherical: 4 # size of the basis set
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: False
  use_pbc: True
#  num_graph_targets: 3

optim:
  batch_size: 8
  # eval_batch_size: 16
  num_workers: 4
  lr_initial: 0.001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 60000
    - 120000
  warmup_steps: 1000
  warmup_factor: 0.2
  max_epochs: 250
  # eval_every: 20
  
checkpoint: ../checkpoints/train/2021-11-22-21-08-00/best_checkpoint.pt
strict_load: False