includes:
# - configs/is2re/100k/binaryCu.yml
  - ../ocp/configs/is2re/all/binaryCu-hpo.yml
  # - /home/chrispr/mem/chrispr/catalysis/ocp/configs/is2re/all/binaryCu-hpo.yml

model:
  name: dimenetplusplus
  hidden_channels: 64
  out_emb_channels: 48
  num_blocks: 3
  cutoff: 7. # should this match the a2g radius in the dataset? probably. or is this for regenerating graph on the fly..
  num_radial: 6 # size of the basis set
  num_spherical: 7 # size of the basis set
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: False
  use_pbc: True

# *** Important note ***
#   The total number of gpus used for this run was 1.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

# optim:
#   batch_size: 12
#   eval_batch_size: 12
#   num_workers: 1
#   lr_initial: 0.0001
#   lr_gamma: 0.1
#   lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
#     - 200000
#     - 400000
#     - 600000
#   warmup_steps: 100000
#   warmup_factor: 0.2
#   max_epochs: 100

optim:
  batch_size: 8
  eval_batch_size: 8
  num_workers: 1
  lr_initial: 0.001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 30000
    - 55000
    - 80000
  warmup_steps: 800
  warmup_factor: 0.2
  max_epochs: 400
  # eval_every: 20