includes:
#   - configs/is2re/10k/base.yml
   - sandbox.yml

model:
  name: dimenetplusplus
  hidden_channels: 64
  out_emb_channels: 48
  num_blocks: 3
  cutoff: 7. # should this match the a2g radius in the dataset? probably. or is this for regenerating graph on the fly..
  num_radial: 6 # size of the basis set
  num_spherical: 7 # size of the basis set
  num_before_skip: 1
  num_after_skip: 2
  num_output_layers: 3
  regress_forces: False
  use_pbc: True


optim:
  batch_size: 16
  # eval_batch_size: 16
  num_workers: 4
  lr_initial: 0.001
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 1000
    - 5000
    - 8000
  warmup_steps: 800
  warmup_factor: 0.2
  max_epochs: 110
  # eval_every: 20
